In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pandas_profiling

In [7]:
Data = pd.read_csv('C:/Users/Praveen1981/Pandas/Data/FuelConsumption.csv')
Data.head()

MODELYEAR   MAKE       MODEL VEHICLECLASS  ENGINESIZE  CYLINDERS  \
0       2014  ACURA         ILX      COMPACT         2.0          4   
1       2014  ACURA         ILX      COMPACT         2.4          4   
2       2014  ACURA  ILX HYBRID      COMPACT         1.5          4   
3       2014  ACURA     MDX 4WD  SUV - SMALL         3.5          6   
4       2014  ACURA     RDX AWD  SUV - SMALL         3.5          6   

  TRANSMISSION FUELTYPE  FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  \
0          AS5        Z                   9.9                  6.7   
1           M6        Z                  11.2                  7.7   
2          AV7        Z                   6.0                  5.8   
3          AS6        Z                  12.7                  9.1   
4          AS6        Z                  12.1                  8.7   

   FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS  
0                   8.5                        33           196  
1                   9.6                        29           221  
2                   5.9                        48           136  
3                  11.1                        25           255  
4                  10.6                        27           244

In [8]:
Data.tail()

MODELYEAR   MAKE     MODEL    VEHICLECLASS  ENGINESIZE  CYLINDERS  \
1062       2014  VOLVO  XC60 AWD     SUV - SMALL         3.0          6   
1063       2014  VOLVO  XC60 AWD     SUV - SMALL         3.2          6   
1064       2014  VOLVO  XC70 AWD     SUV - SMALL         3.0          6   
1065       2014  VOLVO  XC70 AWD     SUV - SMALL         3.2          6   
1066       2014  VOLVO  XC90 AWD  SUV - STANDARD         3.2          6   

     TRANSMISSION FUELTYPE  FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  \
1062          AS6        X                  13.4                  9.8   
1063          AS6        X                  13.2                  9.5   
1064          AS6        X                  13.4                  9.8   
1065          AS6        X                  12.9                  9.3   
1066          AS6        X                  14.9                 10.2   

      FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS  
1062                  11.8                        24           271  
1063                  11.5                        25           264  
1064                  11.8                        24           271  
1065                  11.3                        25           260  
1066                  12.8                        22           294

In [9]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067 entries, 0 to 1066
Data columns (total 13 columns):
MODELYEAR                   1067 non-null int64
MAKE                        1067 non-null object
MODEL                       1067 non-null object
VEHICLECLASS                1067 non-null object
ENGINESIZE                  1067 non-null float64
CYLINDERS                   1067 non-null int64
TRANSMISSION                1067 non-null object
FUELTYPE                    1067 non-null object
FUELCONSUMPTION_CITY        1067 non-null float64
FUELCONSUMPTION_HWY         1067 non-null float64
FUELCONSUMPTION_COMB        1067 non-null float64
FUELCONSUMPTION_COMB_MPG    1067 non-null int64
CO2EMISSIONS                1067 non-null int64
dtypes: float64(4), int64(4), object(5)
memory usage: 108.5+ KB


In [10]:
Data.columns

Index(['MODELYEAR', 'MAKE', 'MODEL', 'VEHICLECLASS', 'ENGINESIZE', 'CYLINDERS',
       'TRANSMISSION', 'FUELTYPE', 'FUELCONSUMPTION_CITY',
       'FUELCONSUMPTION_HWY', 'FUELCONSUMPTION_COMB',
       'FUELCONSUMPTION_COMB_MPG', 'CO2EMISSIONS'],
      dtype='object')

In [11]:
X_Data= Data[['ENGINESIZE', 'CYLINDERS', 'FUELCONSUMPTION_CITY','FUELCONSUMPTION_HWY','FUELCONSUMPTION_COMB',
       'FUELCONSUMPTION_COMB_MPG',]]
X_Data

ENGINESIZE  CYLINDERS  FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  \
0            2.0          4                   9.9                  6.7   
1            2.4          4                  11.2                  7.7   
2            1.5          4                   6.0                  5.8   
3            3.5          6                  12.7                  9.1   
4            3.5          6                  12.1                  8.7   
...          ...        ...                   ...                  ...   
1062         3.0          6                  13.4                  9.8   
1063         3.2          6                  13.2                  9.5   
1064         3.0          6                  13.4                  9.8   
1065         3.2          6                  12.9                  9.3   
1066         3.2          6                  14.9                 10.2   

      FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  
0                      8.5                        33  
1                      9.6                        29  
2                      5.9                        48  
3                     11.1                        25  
4                     10.6                        27  
...                    ...                       ...  
1062                  11.8                        24  
1063                  11.5                        25  
1064                  11.8                        24  
1065                  11.3                        25  
1066                  12.8                        22  

[1067 rows x 6 columns]

In [7]:
Y_Data= Data['CO2EMISSIONS']

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
Reg = LinearRegression()
Reg.fit(X_Data, Y_Data)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
pd.DataFrame({'col':X_Data.columns,
             'Coef':Reg.coef_,
             'Interseption':Reg.intercept_})

col       Coef  Interseption
0                ENGINESIZE   8.577673    253.531201
1                 CYLINDERS   7.698747    253.531201
2      FUELCONSUMPTION_CITY -10.592623    253.531201
3       FUELCONSUMPTION_HWY  -3.489183    253.531201
4      FUELCONSUMPTION_COMB  17.752861    253.531201
5  FUELCONSUMPTION_COMB_MPG  -3.869243    253.531201

In [14]:
Reg.score(X_Data,Y_Data)

0.8892861092642407

In [15]:
from sklearn.model_selection import train_test_split

In [24]:
X_train,X_test,Y_train,Y_test = train_test_split(X_Data,Y_Data)

In [25]:
X_train.shape

(800, 6)

In [26]:
X_test.shape

(267, 6)

In [27]:
Y_train.shape

(800,)

In [28]:
Y_test.shape

(267,)

In [29]:
Multi_Reg = LinearRegression()

In [30]:
Multi_Reg.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [32]:
Multi_Reg.rank_

6

In [33]:
Multi_Reg.coef_

array([  8.72751222,   7.08400918, -14.53004539,  -8.58556696,
        26.7652763 ,  -3.78184312])

In [34]:
Multi_Reg.intercept_

250.85923538626764

In [35]:
New_prediction = Multi_Reg.predict(X_test)

In [36]:
New_prediction[0:5]

array([193.80535077, 212.06618734, 325.83356123, 191.50002788,
       200.13084696])

In [40]:
Multi_Reg.score(X_train,Y_train)

0.8970770736386637

In [39]:
Multi_Reg.score(X_test,Y_test)

0.8641808235490842

In [41]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [42]:
pd.DataFrame({'Actual_Data':Y_test,
             'New_prediction':New_prediction,
             'MSE':mean_squared_error(Y_test,New_prediction),
             'MAE':mean_absolute_error(Y_test,New_prediction)})

Actual_Data  New_prediction         MSE        MAE
979          189      193.805351  529.699578  15.133289
932          207      212.066187  529.699578  15.133289
387          343      325.833561  529.699578  15.133289
792          191      191.500028  529.699578  15.133289
625          205      200.130847  529.699578  15.133289
..           ...             ...         ...        ...
504          198      197.820323  529.699578  15.133289
781          179      182.441849  529.699578  15.133289
160          232      220.090352  529.699578  15.133289
762          278      275.935973  529.699578  15.133289
594          216      216.501375  529.699578  15.133289

[267 rows x 4 columns]

In [43]:
r2_score(Y_test,New_prediction)

0.8641808235490842

In [44]:
from sklearn.model_selection import cross_val_score

In [45]:
cv = cross_val_score(Multi_Reg,X_train,Y_train,cv =10)
cv

array([0.89689152, 0.92576277, 0.89573863, 0.88461566, 0.89236463,
       0.89079302, 0.87331422, 0.86687575, 0.86448382, 0.9285158 ])

In [46]:
np.max(cv)

0.9285158040761793

In [47]:
np.min(cv)

0.8644838249025

In [48]:
np.mean(cv)

0.8919355837631227