In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas_profiling
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [54]:
df = pd.read_csv('https://raw.githubusercontent.com/reddyprasade/Machine-Learning-Repository-DataSets/master/Classification/Weather.csv')
df

Outlook  Temp Humidity Windy Play  Unnamed: 5
0      Rainy   Hot     High     f   no         NaN
1      Rainy   Hot     High     t   no         NaN
2   Overcast   Hot     High     f  yes         NaN
3      Sunny  Mild     High     f  yes         NaN
4      Sunny  Cool   Normal     f  yes         NaN
5      Sunny  Cool   Normal     t   no         NaN
6   Overcast  Cool   Normal     t  yes         NaN
7      Rainy  Mild     High     f   no         NaN
8      Rainy  Cool   Normal     f  yes         NaN
9      Sunny  Mild   Normal     f  yes         NaN
10     Rainy  Mild   Normal     t  yes         NaN
11  Overcast  Mild     High     t  yes         NaN
12  Overcast   Hot   Normal     f  yes         NaN
13     Sunny  Mild     High     t   no         NaN

In [55]:
df.drop('Unnamed: 5',axis=1,inplace=True)

In [56]:
df

Outlook  Temp Humidity Windy Play
0      Rainy   Hot     High     f   no
1      Rainy   Hot     High     t   no
2   Overcast   Hot     High     f  yes
3      Sunny  Mild     High     f  yes
4      Sunny  Cool   Normal     f  yes
5      Sunny  Cool   Normal     t   no
6   Overcast  Cool   Normal     t  yes
7      Rainy  Mild     High     f   no
8      Rainy  Cool   Normal     f  yes
9      Sunny  Mild   Normal     f  yes
10     Rainy  Mild   Normal     t  yes
11  Overcast  Mild     High     t  yes
12  Overcast   Hot   Normal     f  yes
13     Sunny  Mild     High     t   no

In [57]:
df.tail()

Outlook  Temp Humidity Windy Play
9      Sunny  Mild   Normal     f  yes
10     Rainy  Mild   Normal     t  yes
11  Overcast  Mild     High     t  yes
12  Overcast   Hot   Normal     f  yes
13     Sunny  Mild     High     t   no

In [58]:
df.shape

(14, 5)

In [59]:
df.columns

Index(['Outlook', 'Temp', 'Humidity', 'Windy', 'Play'], dtype='object')

In [60]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [61]:
col=df[['Outlook', 'Temp', 'Humidity', 'Windy','Play']]
for i in col:
    df[i]=le.fit_transform(df[i])

In [62]:
df

Outlook  Temp  Humidity  Windy  Play
0         1     1         0      0     0
1         1     1         0      1     0
2         0     1         0      0     1
3         2     2         0      0     1
4         2     0         1      0     1
5         2     0         1      1     0
6         0     0         1      1     1
7         1     2         0      0     0
8         1     0         1      0     1
9         2     2         1      0     1
10        1     2         1      1     1
11        0     2         0      1     1
12        0     1         1      0     1
13        2     2         0      1     0

In [63]:
x=df[['Outlook', 'Temp', 'Humidity', 'Windy']]
x

Outlook  Temp  Humidity  Windy
0         1     1         0      0
1         1     1         0      1
2         0     1         0      0
3         2     2         0      0
4         2     0         1      0
5         2     0         1      1
6         0     0         1      1
7         1     2         0      0
8         1     0         1      0
9         2     2         1      0
10        1     2         1      1
11        0     2         0      1
12        0     1         1      0
13        2     2         0      1

In [93]:
y=df['Play']
y

0     0
1     0
2     1
3     1
4     1
5     0
6     1
7     0
8     1
9     1
10    1
11    1
12    1
13    0
Name: Play, dtype: int32

In [94]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [95]:
x_train.shape

(10, 4)

In [96]:
x_test.shape

(4, 4)

In [97]:
y_train.shape

(10,)

In [98]:
y_test.shape

(4,)

In [99]:
ber=BernoulliNB(1.0)

In [100]:
ber

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [101]:
ber.fit(x_train,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [102]:
ber.coef_

array([[-0.33647224, -0.33647224, -0.55961579, -0.84729786]])

In [103]:
ber.intercept_

array([-0.69314718])

In [104]:
ber.score(x_train,y_train)

0.7

In [105]:
ber.score(x_test,y_test)

1.0

In [106]:
pred=ber.predict(x_test)

In [107]:
pred[:5]

array([1, 1, 1, 1])

In [108]:
pd.DataFrame({'newly predicted':pred,
              'y_test':y_test})

newly predicted  y_test
8                 1       1
12                1       1
6                 1       1
2                 1       1

In [109]:
model = MultinomialNB(alpha=10)

In [110]:
model.fit(x_train,y_train)

MultinomialNB(alpha=10, class_prior=None, fit_prior=True)

In [111]:
model.intercept_

array([-0.69314718])

In [112]:
model.coef_

array([[-1.26113122, -1.2039728 , -1.5293952 , -1.60943791]])

In [113]:
model.score(x_train,y_train)

0.8

In [114]:
model.score(x_test,y_test)

0.75

In [115]:
y_pred=model.predict(x_test)

In [116]:
y_pred

array([1, 1, 0, 1])

In [124]:
pd.DataFrame({'predicted value':y_pred,
              'acutal values':y_test})

predicted value  acutal values
8                 1              1
12                1              1
6                 0              1
2                 1              1

In [118]:
gua_model = GaussianNB()

In [119]:
gua_model.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [120]:
gua_model.score(x_train,y_train)

0.8

In [121]:
gua_model.score(x_test,y_test)

1.0

In [122]:
gua_predict= gua_model.predict(x_test)

In [125]:
pd.DataFrame({'new_predict':gua_predict,
             'actual values':y_test})

new_predict  actual values
8             1              1
12            1              1
6             1              1
2             1              1